[package]
name = "replicante_stream_events"
version = "0.1.1"
authors = ["Stefano Pogliani <stefano@spogliani.net>"]
edition = "2018"

description = "Replicante streaming interface for events"
documentation = "https://www.replicante.io/docs"
homepage = "https://www.replicante.io/"
repository = "https://github.com/replicante-io/replicante"
license = "MIT"


[features]
with_test_support = ["replicante_stream/with_test_support"]


[dependencies]
opentracingrust = "^0.3.3"
slog = "^2.1.1"

replicante_models_core = { path = "../../models/core" }
replicante_service_healthcheck = { path = "../../service/healthcheck" }
replicante_stream = { path = "../stream" }
