[package]
name = "replicante"
version = "0.1.0"
authors = ["Stefano Pogliani <stefano@spogliani.net>"]
build = "build.rs"

description = "Safe DataStore automation"
documentation = "https://www.replicante.io/docs"
homepage = "https://www.replicante.io/"
repository = "https://github.com/replicante-io/replicante"
readme = "Readme.md"
keywords = ["automation", "datastore", "operations"]
license = "MIT"


[[bin]]
name = "replicante"
path = "src/main.rs"


[lib]
name = "replicante"
path = "src/lib.rs"


[badges]
maintenance = { status = "actively-developed" }


[dependencies]
clap = "^2.31.2"
error-chain = "^0.11.0"
serde = "^1.0.34"
serde_derive = "^1.0.34"
serde_yaml = "^0.7.3"


[build-dependencies]
git2 = "^0.7.0"


#[workspace]
#members = [
#  "."
#]
