[workspace]
members = [
  "agent/client",
  "agent/discovery",
  "bin/replicante",
  "bin/replictl",
  "common/logging",
  "common/models/agent",
  "common/models/api",
  "common/util/failure",
  "common/util/iron",
  "common/util/rndid",
  "common/util/tracing",
  "common/util/upkeep",
  "coordinator",
  "data/aggregator",
  "data/fetcher",
  "data/models",
  "data/store",
  "service/healthcheck",
  "streams/events",
  "tasks",
]

# This patch is needed to make openssl (needed by kafka) work with openssl 1.0+
[patch.crates-io]
kafka = { git = 'https://github.com/l4l/kafka-rust', branch = 'update/openssl' }
