[package]
name = "unamed"
version = "0.1.0"
authors = ["Stefano Pogliani <stefano@spogliani.net>"]

[[bin]]
name = "unamed-core"
path = "core/bin/main.rs"

[dependencies]
unamed_agent = { path = "agent/base" }

[workspace]
