[workspace]
members = [
  "agent/client",
  "bin/repliadm",
  "bin/replicante",
  "bin/replictl",
  "cluster/aggregator",
  "cluster/discovery",
  "cluster/fetcher",
  "core/components/discovery",
  "core/components/viewupdater",
  "core/tasks/discovery",
  "externals/kafka",
  "externals/mongodb",
  "models/core",
  "models/tasks",
  "service/coordinator",
  "service/healthcheck",
  "service/tasks",
  "store/primary",
  "store/view",
  "stream/events",
  "stream/stream",
]
