[workspace]
members = [
  "agent/client",
  "bin/replicante",
  "bin/replictl",
  "cluster/aggregator",
  "cluster/discovery",
  "cluster/fetcher",
  "common/logging",
  "common/models/agent",
  "common/models/api",
  "common/util/failure",
  "common/util/iron",
  "common/util/rndid",
  "common/util/tracing",
  "common/util/upkeep",
  "externals/kafka",
  "externals/mongodb",
  "models/core",
  "service/coordinator",
  "service/healthcheck",
  "service/tasks",
  "store/primary",
  "store/view",
  "stream/events",
  "stream/stream",
]
