[workspace]
members = [
  "agent/client",
  "agent/discovery",
  "common/agent/models",
  "common/logging",
  "common/util/iron",
  "common/util/tracing",
  "data/aggregator",
  "data/fetcher",
  "data/models",
  "data/store",
  "replicante",
  "replictl",
  "streams/events",
]
