version: '3.5'


services:
  mongo:
    command:
      - 'mongod'
      - '--replSet'
      - 'replistore'
      - '--bind_ip'
      - '0.0.0.0'
    image: mongo:4.0
    hostname: mongo
    ports:
      - '27017:27017'
    volumes:
      - type: volume
        source: mongo
        target: /data/db

  mongoui:
    environment:
      CONN_NAME: 'replistore'
      DB_HOST: 'mongo'
      PORT: '4321'
    image: 'mrvautin/adminmongo:latest'
    hostname: mongoui
    ports:
      - '4321:4321'


volumes:
  mongo:
