version: '3.5'


services:
  mongo:
    command:
      - 'mongod'
      - '--replSet'
      - 'replistore'
      - '--bind_ip'
      - '0.0.0.0'
    image: mongo:4.0
    hostname: mongo
    ports:
      - '27017:27017'
    volumes:
      - type: volume
        source: mongo
        target: '/data/db'

  mongoui:
    command:
      - 'sh'
      - '-c'
      - 'sleep 30 && node app.js'
    depends_on:
      - mongo
    environment:
      PORT: '4321'
    image: 'mrvautin/adminmongo:latest'
    hostname: mongoui
    ports:
      - '4321:4321'
    volumes:
      - type: bind
        source: './devtools/mongoui.connections.json'
        target: '/app/user/config/config.json'
        read_only: true

  prometheus:
    image: 'prom/prometheus:v2.4.3'
    hostname: prometheus
    ports:
      - '9090:9090'
    volumes:
      - type: bind
        source: './devtools/prometheus.yml'
        target: '/etc/prometheus/prometheus.yml'
        read_only: true
      - type: volume
        source: prometheus
        target: '/prometheus'


networks:
  default:
    ipam:
      config:
        - subnet: 172.128.0.0/27


volumes:
  mongo:
  prometheus:
