version: '3'


services:
  mongo:
    command:
      - 'mongod'
      - '--replSet'
      - 'persistence'
    image: mongo:3.6
    hostname: mongo
    ports:
      - '27017:27017'
    volumes:
      - './devtools/data/mongo:/data/db'
