#################################################
# Essential dependencies to run Replicante Core #
#################################################
version: '3.7'


services:
  kafka:
    environment:
      JMX_PORT: 9999
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://172.128.0.254:9092
      KAFKA_LOG_FLUSH_SCHEDULER_INTERVAL_MS: 60000
      KAFKA_NUM_PARTITIONS: 4
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181/kafka'
    hostname: kafka
    image: wurstmeister/kafka:2.11-2.0.0
    init: true
    links:
      - zookeeper
    networks:
      default:
        ipv4_address: '172.128.0.254'
    ports:
      - '9092:9092'
    volumes:
      - type: volume
        source: kafka
        target: /kafka

  mongo:
    command:
      - 'mongod'
      - '--replSet'
      - 'replistore'
      - '--bind_ip'
      - '0.0.0.0'
    hostname: mongo
    image: mongo:4.0
    init: true
    ports:
      - '27017:27017'
    volumes:
      - type: volume
        source: mongo
        target: '/data/db'
      - type: bind
        source: './devtools/provisioning/mongo'
        target: '/replicore'
        read_only: true

  zookeeper:
    environment:
      ZOO_MY_ID: 1
    hostname: 'zookeeper'
    image: 'zookeeper:3.4'
    init: true
    ports:
      - '2181:2181'
    volumes:
      - type: volume
        source: zkdata
        target: '/data'
      - type: volume
        source: zklog
        target: '/datalog'
      - type: bind
        source: './devtools/provisioning/zookeeper.conf'
        target: '/conf/zoo.cfg'
        read_only: false

  static_server:
    hostname: 'static_server'
    image: 'nginx:1.17'
    init: true
    ports:
      - '8081:80'
    volumes:
      - type: bind
        source: './devtools/static_server/'
        target: '/usr/share/nginx/html'
        read_only: true


networks:
  default:
    # Use a known IP range so some addresses can be fixed.
    # Fixed addresses are useful to allow the host to find containers by IP
    # (for example kafka-rest) of for tools that broadcast their IP as a form
    # of service discovery (for example kafka).
    #
    # Known containers with fixed IPs:
    #
    #   - 172.128.0.254: kafka
    ipam:
      config:
        - subnet: 172.128.0.0/24


volumes:
  kafka: {}
  mongo: {}
  zkdata: {}
  zklog: {}
