version: '3.5'


services:
  mongo:
    command:
      - 'mongod'
      - '--replSet'
      - 'datastore'
      - '--bind_ip'
      - '0.0.0.0'
    image: mongo:4.0
    hostname: mongo
    ports:
      - '27017:27017'
    volumes:
      - type: volume
        source: mongo
        target: /data/db


volumes:
  mongo:
