version: '3.5'


services:
  grafana:
    environment:
      GF_INSTALL_PLUGINS: 'grafana-simple-json-datasource'
    image: 'grafana/grafana:5.3.0'
    hostname: grafana
    ports:
      - '3000:3000'
    volumes:
      - type: volume
        source: grafana
        target: '/var/lib/grafana'
      - type: bind
        source: './devtools/grafana/provisioning'
        target: '/etc/grafana/provisioning'


volumes:
  grafana:
