#################################################
# Essential dependencies to run Replicante Core #
#################################################
version: '3.5'


services:
  kafka:
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://172.128.0.30:9092
      KAFKA_LOG_FLUSH_SCHEDULER_INTERVAL_MS: 60000
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181/kafka'
      JMX_PORT: 9999
    hostname: kafka
    image: wurstmeister/kafka:2.11-2.0.0
    links:
      - zookeeper
    networks:
      default:
        ipv4_address: '172.128.0.30'
    ports:
      - '9092:9092'
    volumes:
      - type: volume
        source: kafka
        target: /kafka

  mongo:
    command:
      - 'mongod'
      - '--replSet'
      - 'replistore'
      - '--bind_ip'
      - '0.0.0.0'
    hostname: mongo
    image: mongo:4.0
    ports:
      - '27017:27017'
    volumes:
      - type: volume
        source: mongo
        target: '/data/db'

  zookeeper:
    environment:
      ZOO_MY_ID: 1
    hostname: 'zookeeper'
    image: 'zookeeper:3.4'
    ports:
      - '2181:2181'
    volumes:
      - type: volume
        source: zkdata
        target: '/data'
      - type: volume
        source: zklog
        target: '/datalog'
      - type: bind
        source: './devtools/provisioning/zookeeper.conf'
        target: '/conf/zoo.cfg'
        read_only: false


networks:
  default:
    ipam:
      config:
        - subnet: 172.128.0.0/27


volumes:
  kafka: {}
  mongo: {}
  zkdata: {}
  zklog: {}
