version: '3.5'


services:
  mongo:
    command:
      - 'mongod'
      - '--replSet'
      - 'replistore'
      - '--bind_ip'
      - '0.0.0.0'
    image: mongo:4.0
    hostname: mongo
    ports:
      - '27017:27017'
    volumes:
      - type: volume
        source: mongo
        target: /data/db

  mongoui:
    depends_on:
      - mongo
    environment:
      PORT: '4321'
    image: 'mrvautin/adminmongo:latest'
    hostname: mongoui
    ports:
      - '4321:4321'
    volumes:
      - type: bind
        source: './devtools/mongoui.connections.json'
        target: '/app/user/config/config.json'
        read_only: true


volumes:
  mongo:
