[package]
name = "replidev"
version = "0.1.0"
authors = ["Stefano Pogliani <stefano@spogliani.net>"]
edition = "2018"
build = "../../build.rs"

description = "Replicante Development Tool"
documentation = "https://www.replicante.io/docs"
homepage = "https://www.replicante.io/"
repository = "https://github.com/replicante-io/replicante"
readme = "./README.md"
license = "MIT"


[[bin]]
name = "replidev"
path = "src/main.rs"


[lib]
name = "replidev"
path = "src/lib.rs"


[dependencies]
failure = "^0.1.5"
lazy_static = "^1.4.0"
pnet_datalink = "^0.25"
prettytable-rs = "^0.8"
serde = "^1.0.105"
serde_yaml = "^0.8.11"
structopt = "^0.3.0"

replicante_util_failure = { path = "../../common/util/failure" }


[build-dependencies]
git2 = "^0.13.0"


[workspace]
