[package]
name = "replidev"
version = "0.1.0"
authors = ["Stefano Pogliani <stefano@spogliani.net>"]
edition = "2018"
build = "../../build.rs"

description = "Replicante Development Tool"
documentation = "https://www.replicante.io/docs"
homepage = "https://www.replicante.io/"
repository = "https://github.com/replicante-io/replicante"
readme = "./README.md"
license = "MIT"


[[bin]]
name = "replidev"
path = "src/main.rs"


[lib]
name = "replidev"
path = "src/lib.rs"


[dependencies]
actix-rt = "^1.0.0"
actix-web = "^2.0.0"
failure = "^0.1.5"
handlebars = "^3.0.0"
lazy_static = "^1.4.0"
pnet_datalink = "^0.26.0"
prettytable-rs = "^0.8.0"
rand = "^0.7.0"
serde = "^1.0.105"
serde_json = "^1.0.0"
serde_yaml = "^0.8.11"
structopt = "^0.3.0"
tokio = { version = "^0.2.0", features = ["full"] }

replicante_models_core = { path = "../../models/core" }
replicante_util_failure = { path = "../../common/util/failure" }


[build-dependencies]
git2 = "^0.13.0"


[workspace]
