[package]
name = "replicante_agent_client"
version = "0.2.0"
authors = ["Stefano Pogliani <stefano@spogliani.net>"]

description = "HTTP client for Replicante Agents"
documentation = "https://www.replicante.io/docs"
homepage = "https://www.replicante.io/"
repository = "https://github.com/replicante-io/replicante"
keywords = ["automation", "datastore", "operations"]
license = "MIT"


[badges]
maintenance = { status = "actively-developed" }


[dependencies]
error-chain = "^0.12.0"
lazy_static = "^1.0.0"
prometheus = "^0.5.0"
reqwest = "^0.9.1"
serde = "^1.0.34"
serde_derive = "^1.0.34"
slog = "^2.2.0"

replicante_agent_models = { path = "../../common/agent/models" }
