[package]
name = "replicante_store_view"
version = "0.1.0"
authors = ["Stefano Pogliani <stefano@spogliani.net>"]
edition = "2018"

description = "Replicante api/view only store interface"
documentation = "https://www.replicante.io/docs"
homepage = "https://www.replicante.io/"
repository = "https://github.com/replicante-io/replicante"
license = "MIT"


[features]
with_test_support = []


[dependencies]
bson = "^0.14.0" # bound by mongodb crate
chrono = "^0.4.6"
failure = "^0.1.5"
lazy_static = "^1.0.0"
mongodb = "^0.4.0"
opentracingrust = "^0.3.3"
serde = "^1.0.34"
serde_derive = "^1.0.34"
slog = "^2.2.0"

replicante_externals_mongodb = { path = "../../externals/mongodb" }
replicante_models_core = { path = "../../models/core" }
replicante_service_healthcheck = { path = "../../service/healthcheck" }
