[package]
name = "replicante_store_primary"
version = "0.4.0"
authors = ["Stefano Pogliani <stefano@spogliani.net>"]
edition = "2018"

description = "Replicante primary data store interface"
documentation = "https://www.replicante.io/docs"
homepage = "https://www.replicante.io/"
repository = "https://github.com/replicante-io/replicante"
license = "MIT"


[features]
with_test_support = []


[dependencies]
chrono = { version = "^0.4.0", features = ["serde"] }
bson = "^0.14.0" # bound by mongodb crate
failure = "^0.1.5"
lazy_static = "^1.0.0"
mongodb = "^0.9.2"
opentracingrust = "^0.4.0"
regex = "^1.0.0"
serde = "^1.0.34"
serde_derive = "^1.0.34"
serde_json = "^1.0.39"
slog = "^2.2.0"
uuid = { version = "^0.8.0", features = ["serde", "v4"] }

replicante_externals_mongodb = { path = "../../externals/mongodb" }
replicante_models_api = { path = "../../common/models/api" }
replicante_models_core = { path = "../../models/core" }
replicante_service_healthcheck = { path = "../../service/healthcheck" }
replicante_util_tracing = { path = "../../common/util/tracing" }
