#################################################
# Jaeger All-In-One tracer (no persisted state) #
#################################################
version: '3.7'


services:
  jaeger:
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    image: jaegertracing/all-in-one:1.12
    ports:
      - 5778:5778
      - 9411:9411
      - 14268:14268
      - 16686:16686
