################################
# WebUI tools for dependencies #
################################
#
# Services:
#   * Kafka Topics Viewer (https://github.com/Landoop/kafka-topics-ui)
#   * MongoDB UI (https://mrvautin.com/adminmongo/)
#   * Zookeeper Navigator (https://www.elkozmon.com/zoonavigator/)
version: '3.7'


services:
  kafkaui:
    depends_on:
      - zookeeper
      - kafka
    environment:
      JVM_OPTS: '-Xms32M -Xmx64M'
      KAFKA_BROKERCONNECT: 'kafka:9092'
      ZOOKEEPER_CONNECT: 'zookeeper:2181/kafka'
    hostname: 'kafkaui'
    image: 'obsidiandynamics/kafdrop'
    init: true
    ports:
      - '8001:9000'

  mongoui:
    command:
      - 'sh'
      - '-c'
      - 'sleep 30 && node app.js'
    depends_on:
      - mongo
    environment:
      HOST: '0.0.0.0'
      PORT: '4321'
    hostname: mongoui
    image: 'mrvautin/adminmongo:latest'
    init: true
    ports:
      - '4321:4321'
    stop_grace_period: 1s
    volumes:
      - type: bind
        source: './devtools/provisioning/mongoui/connections.json'
        target: '/app/user/config/config.json'
        read_only: true

  zoonavigator-api:
    environment:
      API_HTTP_PORT: 9000
    hostname: zoonavigator-api
    image: elkozmon/zoonavigator-api:0.5.0
    init: true

  zoonavigator-web:
    environment:
      AUTO_CONNECT_CONNECTION_STRING: 'zookeeper:2181'
      WEB_HTTP_PORT: 8000
      API_HOST: 'zoonavigator-api'
      API_PORT: 9000
    hostname: zoonavigator-web
    image: elkozmon/zoonavigator-web:0.5.0
    init: true
    links:
      - zoonavigator-api
      - zookeeper
    ports:
      - '8000:8000'
