[package]
name = "replictl"
version = "0.5.0"
authors = ["Stefano Pogliani <stefano@spogliani.net>"]
edition = "2018"
build = "../../build.rs"

description = "Replicante Core command line tool"
documentation = "https://www.replicante.io/docs"
homepage = "https://www.replicante.io/"
repository = "https://github.com/replicante-io/replicante"
readme = "../../README.md"
license = "MIT"


[[bin]]
name = "replictl"
path = "src/main.rs"


[lib]
name = "replictl"
path = "src/lib.rs"


[dependencies]
clap = "^2.31.2"
dialoguer = "^0.6.0"
dirs = "^2.0.2"
failure = "^0.1.3"
futures = "^0.3.4"
serde = { version = "^1.0.34", features = ["derive"] }
serde_json = "^1.0.0"
serde_yaml = "^0.8.0"
slog = "^2.1.1"
slog-json = "^2.3.0"
uuid = { version = "^0.8.0", features = ["serde", "v4"] }

replicante_models_core = { path = "../../models/core" }
replicante_util_failure = { path = "../../common/util/failure" }

[dependencies.reqwest]
# Use rustls-tls to access PEM files as Identity objects.
features = ["rustls-tls", "blocking"]
version = "^0.10.4"


[build-dependencies]
git2 = "^0.13.0"
