[package]
name = "replicante_externals_kafka"
version = "0.1.1"
authors = ["Stefano Pogliani <stefano@spogliani.net>"]
edition = "2018"

description = "Replicante reusable logic for Kafka"
documentation = "https://www.replicante.io/docs"
homepage = "https://www.replicante.io/"
repository = "https://github.com/replicante-io/replicante"
license = "MIT"


[dependencies]
failure = "^0.1.5"
lazy_static = "^1.0.0"
prometheus = "^0.8.0"
rdkafka = "^0.23.0"
serde = "^1.0.34"
serde_derive = "^1.0.34"
slog = "^2.2.0"

replicante_models_api = { path = "../../common/models/api" }
replicante_service_healthcheck = { path = "../../service/healthcheck" }
