[package]
name = "replicante_stream"
version = "0.1.0"
authors = ["Stefano Pogliani <stefano@spogliani.net>"]
edition = "2018"

description = "Replicante common streaming logic"
documentation = "https://www.replicante.io/docs"
homepage = "https://www.replicante.io/"
repository = "https://github.com/replicante-io/replicante"
keywords = ["replicante"]
license = "MIT"


[features]
with_test_support = ["crossbeam-channel"]


[dependencies]
crossbeam-channel = { version = "^0.3.8", optional = true }
failure = "^0.1.5"
futures = "^0.1.25"
humthreads = "^0.1.4"
lazy_static = "^1.0.0"
opentracingrust = "^0.3.3"
prometheus = "^0.7.0"
rand = "^0.7.0"
rdkafka = "^0.21.0"
sentry = "^0.17.0"
serde = "^1.0.34"
serde_derive = "^1.0.34"
serde_json = "^1.0.39"
slog = "^2.1.1"

replicante_externals_kafka = { path = "../../externals/kafka" }
replicante_service_healthcheck = { path = "../../service/healthcheck" }
replicante_util_failure = { path = "../../common/util/failure" }


[dev-dependencies]
humthreads = { version = "^0.1.4", features = ["with_test_support"] }
